### ISSUE TITLE
FR: Option to apply to folder backgroud instead of text. 

### ISSUE THREAD

**Issue by brimwats** [ecustic/obsidian-file-color#3]
I am really excited for this plugin because I hate maintaining a bunch of CSS snippets. I'd love to also be able to cover the background or the text (or perhaps both?). I think it would make sense to choose via style settings maybe?

feel free to close this if it's out of scope

**Comment by ryadaj** [comment]
+ 1

**Comment by Thomas-Schmall** [comment]
Yes, I second this one. It makes it nicer looking and more visible.

I did it for now with a CSS snippet. 
Works smoothly so far - shouldn't be too hard to convert this into a settings-toggle.
Even cooler would be an additional transparency setting.

```css
.workspace-leaf-content[data-type="file-explorer"] .nav-files-container .nav-folder-title.file-color-file,
.workspace-leaf-content[data-type="file-explorer"] .nav-files-container .nav-file-title.file-color-file 
{
    background-color: var(--file-color-color);
    color: var(--file-color);
}

````

Here is a screenshot in the default theme:

<img src="https://github.com/ecustic/obsidian-file-color/assets/122365531/4093b136-3c32-4976-bd03-ea350a8bb707" width=75% height=75% alt="Obsidian-File-Color-Background-Css" >

**Comment by Thomas-Schmall** [comment]
A little update - since I got some CSS code from eblanshey for implementing this.
 
- Top folders have the background (plus a slight transparency).
- Sub-folders are now bordered in the color and have the text in color. Plus a smidgeon of background.
- Folders only are text-colored. 

For my taste, this helps the readability of the file-explorer a lot.
![obsidian_-_file-color_snippet_for_subfolders-_default_theme](https://github.com/ecustic/obsidian-file-color/assets/122365531/7d4d0fd0-bd44-4b97-8927-a49a6977631c)

Here's the code I used (hacky, use with discretion 😁)

```css
.workspace-leaf-content[data-type="file-explorer"] .nav-files-container .mod-root > .nav-folder-children > .nav-folder > .nav-folder-title {
background-color: var(--file-color-color); 
color: var(--text-normal);
opacity: 0.85;
}

.workspace-leaf-content[data-type="file-explorer"] .nav-files-container :not(.mod-root) > .nav-folder-children > .nav-folder > :not(.nav-file-title).nav-folder-title {
 background-color: rgba(80, 170, 255, 0.03);
border-style: dotted;
border-width: 1px;
border-color: var(--file-color-color); 
}
```
